# fly.toml app configuration file generated for tennis-api on 2025-08-11T23:43:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tennis-api'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3500
  force_https = true
  min_machines_running = 0
  auto_stop_machines = "suspend"
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source="cache_data"
  destination="/data"
